version: "3"

services:

  app:
    container_name: msorder
    image: andreriggs/ms-order:latest
    restart: always
    ports:
      - "80:8080"
    environment:
      TZ: "America/Sao_Paulo"
      SERVER_PORT: 8080
      DATABASE_URL: jdbc:postgres://admin:admin@db:5432/msorder
    volumes:
      - ../target:/opt/app
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
