version: "3"

services:
  broker:
    container_name: 'rabbitmq'
    image: rabbitmq:3-management-alpine
    hostname: "rabbit"
    labels:
      NAME: "rabbitmq"
    restart: always
    environment:
      TZ: "America/Sao_Paulo"
      DEFAULT_VHOST: /
      DEFAULT_USER: 'guest'
      DEFAULT_PASS: 'guest'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
      - "./rabbitmq/data/:/var/lib/rabbitmq"
    networks:
      - docker-network
  db:
    container_name: postgres-db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      TZ: "America/Sao_Paulo"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "msorder"
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
