server:
  port: ${SERVER_PORT}

spring:

  application:
    name: @project.name@
    version: @project.version@

  mvc.favicon.enabled: false

  config:
    activate:
      on-profile:
        - qa

  main:
    banner-mode: CONSOLE