server:
  port: 8080
  shutdown: graceful

spring:

  application:
    name: ms-order

  profiles:
    active: ${ACTIVE_PROFILE:test}
    include:
    - application-test
    - application-dev
    - application-prod

  mvc.favicon.enabled: false

  main:
    banner-mode: CONSOLE