version: "3"
services:
    app:
        container_name: msorder
        image: andreriggs/msorder
        build: ""
        ports:
            - "8080:8080"
        environment:
            - APP_PROFILE=dev
            - DATABASE_URL=jdbc:postgres://postgres:postgres@192.168.10.78:5432/msorder
        volumes:
            - ../target:/opt/app
        links:
            - db
            - broker
        depends_on:
            - db
            - broker
        entrypoint: /bin/sh
        networks:
            - ms-network

    broker:
        image: rabbitmq:3-management-alpine
        container_name: 'rabbitmq'
        hostname: "rabbit"
        labels:
            NAME: "rabbitmq"
        restart: always
        environment:
            DEFAULT_VHOST: /
            DEFAULT_USER: 'guest'
            DEFAULT_PASS: 'guest'
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - "./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
            - "./rabbitmq/data/:/var/lib/rabbitmq"
        networks:
            - ms-network
    db:
        image: postgres:13-alpine
        container_name: postgres
        restart: unless-stopped
        ports:
            - "5432:5432"
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=postgres
        networks:
            - ms-network

networks:
    ms-network:
        driver: bridge
